config/routes.rb
Rails.application.routes.draw do
  resources :certs
  resources :profiles
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"

end

app/models/cert.rb
class Cert < ActiveRecord::Base
	belongs_to :user
	
	#has_attached_file :image
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif","image/pdf"]

  has_attached_file :document
	validates_attachment :document, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}
end

app/models/profile.rb
class Profile < ActiveRecord::Base
		belongs_to :user

		has_attached_file :image

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  has_many :certs


  def has_profile
  	profile != nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/certs_controller.rb
class CertsController < ApplicationController
  before_action :set_cert, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @certs = Cert.all
  end

  def show
  end

  def new
    @cert = current_user.certs.build
  end

  def edit
  end

  def create
    @cert = current_user.certs.build(cert_params)

    respond_to do |format|
      if @cert.save
        format.html { redirect_to profiles_path, notice: 'Employment verification form was successfully uploaded.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @cert.update(cert_params)
        format.html { redirect_to profiles_path, notice: 'Employment verification form was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @cert.destroy
    respond_to do |format|
      format.html { redirect_to certs_url, notice: 'Employment verification form was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cert
      @cert = Cert.find(params[:id])
    end

    def correct_user
      @cert = current_user.certs.find_by(id: params[:id])
      redirect_to certs_path, notice: "Not authorized to edit this cert" if @cert.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cert_params
      params.require(:cert).permit(:description, :document)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to new_cert_url, notice: 'Employment information successfully added.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to new_cert_url, notice: 'Employment information was successfully edited.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:employment, :loans, :amount, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certs_helper.rb
module CertsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/certs/_form.html.erb
<%= form_for @cert, html: { multipart: true } do |f| %>
  <% if @cert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cert.errors.count, "error") %> prohibited this cert from being saved:</h2>

      <ul>
      <% @cert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Choose_File %><br>
    <%= f.file_field :document, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Brief_Description_for_your_records %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="CTA">
    <p><%= f.submit "Upload My Form", class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

app/views/certs/edit.html.erb
<div class="container">
  <div class="jumbotron app center">
		<h1>Editing Cert</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @cert %> |
		<%= link_to 'Back', certs_path %>
	</div>
</div>

app/views/certs/index.html.erb
<div class="container">
  <div class="jumbotron app center">
    <h2>Your Completed Forms</h2>
    <% @certs.each do |cert| %>
      <% if cert.user == current_user %>
        <div class="container">
          <div class="row">
            <div class="pad40"></div>
            <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1">
              <div class="about-text-explanation">
              <span style="font-size:30px;" class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp;
              <%= cert.description %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="about-text-explanation">
              <%= link_to 'Download', "#" %>
              &nbsp;&nbsp;&nbsp;
              <%= link_to 'Delete', cert, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            </div>
          </div>
        </div>
      <% end %>  
    <% end %>
    <br>
    <%= link_to 'Add New Form', new_cert_path, class: "btn btn-primary btn-md" %>
  </div>
</div>

app/views/certs/new.html.erb
<div class="container">
	<div class="jumbotron app center">
		<h4>Progress</h4>
		<div class="row bs-wizard" style="border-bottom:0;">
	    <div class="col-xs-2 col-xs-offset-3 bs-wizard-step complete">
	      <div class="progress"><div class="progress-bar"></div></div>
	        <div class="bs-wizard-dot">
	          <span class="bs-wizard-step-num">1</span>
	          <span class="glyphicon glyphicon-ok progress" aria-hidden="true"></span>
	          <div class="pad5"></div>
	        	<div class="bs-wizard-info pull-left">Eligibility</div>
	        </div>
	      </div>
	      <div class="col-xs-2 bs-wizard-step active"><!-- complete --> 
	        <div class="progress"><div class="progress-bar"></div></div>
	        <div class="bs-wizard-dot">
	          <span class="bs-wizard-step-num">2</span>
	        </div>
	        <div class="bs-wizard-info text-center">Forms</div>
	      </div>
	      <div class="col-xs-2 bs-wizard-step disabled"><!-- complete --> 
	        <div class="progress"><div class="progress-bar"></div></div>
	        <div class="bs-wizard-dot">
	          <span class="bs-wizard-step-num">3</span>
	          <div class="bs-wizard-info pull-right">Tracking</div>
	        </div>
	      </div>
	  	</div> 
		<div class="pad20"></div>
		<div class="text-explanation-cert">
      <% if current_user.profile == nil %>
        <%= link_to "Add Eligibility Inputs", new_profile_path, class: "btn btn-primary btn-md" %>
      <% else %>
        <% if (current_user.profile.employment == 'Government (fed, state, or local)' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'Government (fed, state, or local)' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'Government (fed, state, or local)' && current_user.profile.loans == "I don't know") || (current_user.profile.employment == 'Not-for-profit (Section 501(c)(3))' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'Not-for-profit (Section 501(c)(3))' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'Not-for-profit (Section 501(c)(3))' && current_user.profile.loans == "I don't know") || (current_user.profile.employment == 'AmeriCorps or Peace Corps' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'AmeriCorps or Peace Corps' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'AmeriCorps or Peace Corps' && current_user.profile.loans == "I don't know") || (current_user.profile.employment == 'Other qualifying public services' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'Other qualifying public services' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'Other qualifying public services' && current_user.profile.loans == "I don't know") %>
          <h1>Congratulations!</h1>
          <p>It looks like you may qualify for Public Service Loan Forgiveness! Now...</p>
					<div class="pad30"></div> 
          <div class="container">
				    <div class="row">
				      <div class="explanation center">
				        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
				        	<h2>1. Download Employment Verification Form</h2>
				        	<div class="media">
            				<div class="media-center">
              				<a href="https://studentaid.ed.gov/sa/sites/default/files/public-service-employment-certification-form.pdf", target= "_blank">
                			<span class="glyphicon glyphicon-download-alt" alt="PSLF Employment Verification Form">
              				</a>
            				</div>
            			</div>
            			<div class="pad10"></div> 
            			<div class="media-body">
              			<div class="text-explanation-cert"> Click the icon above (opens new tab) to retrieve the Employment Verification Form. Fill out the portions you can, then have your employer verify and sign the remaining sections.</div>
            			</div>
				        </div>
				      </div>
				    </div>
				  </div>
				  <div class="pad50"></div> 
				  <div class="container">
				    <div class="row">
				      <div class="explanation center">
				        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
				          <h2>2. Upload Completed Form <span style="font-size:14px; vertical-align: text-top;"  class="glyphicon glyphicon-info-sign" aria-hidden="true" role="button" data-toggle="popover" data-trigger="click" data-placement="top" title="Upon Submission..." data-content="we’ll send your completed form to FedLoan Servicing (PHEAA), the U.S. Department of Education’s federal loan servicer for the PSLF Program. FedLoan Servicing will: 1) Review your form for completion, validity, and eligiblity. 2) Notify you about whether additional information needs to be provided to verify the eligibility of your employment. 3) Transfer any loans serviced by another servicer to FedLoan. 4) Review your payment history for previously made qualify payments. 5) Contact you with a summary of their findings."></span>
				          </h2>
				          <p>Once you and your employer have completed the form, upload and submit it below and we will send it to PHEAA (the federal agency that monitors the benefit) on your behalf.</p>
				        <div class="pad10"></div>
          			<%= render 'form' %>
				        </div>
				      </div>
				    </div>
				  </div>
        <% else %>
          <%= "Unfortunately, based on your Eligibility Inputs it seems like you may not be eligible for Public Service Loan Forgiveness at this time. You can review the requirements here." %>
        <% end %>
      <% end %>
    </div>
		<div class="pad10"></div>
		<%= link_to 'Edit my employment and loan information', edit_profile_path(current_user.profile) %>
	</div>
</div>

app/views/certs/show.html.erb
<div class="container">
  <div class="jumbotron app center">
		<p id="notice"><%= notice %></p>

		<p>
		  <strong>Description:</strong>
		  <%= @cert.description %>
		</p>

		<%= link_to 'Edit', edit_cert_path(@cert) %> |
		<%= link_to 'Back', certs_path %>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
	<div class="container"
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <%= link_to image_tag('Gradible-Logo-Grey.png'), root_path, class: "navbar-brand" %>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav navbar-right">
	      <li><%= link_to "Home", root_path %></li>
	      <li><%= link_to "About", "#" %></li>
	      <% if user_signed_in? %>
          <li><%= link_to "Dashboard", profiles_path %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %> 
	    </ul>
	  </div><!-- /.navbar-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Pslf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
  <% if current_page?(root_path) %>
    <%= render 'layouts/header' %>
  <% elsif current_page?(profiles_path) %>
    <%= render 'layouts/dash_header' %>
  <% elsif current_page?(certs_path) %>
    <%= render 'layouts/forms_header' %> 
  <% elsif current_page?(edit_user_registration_path) %>
    <%= render 'layouts/account_header' %> 
  <% elsif current_page?(about_path) %>
    <%= render 'layouts/about_header' %>
  <% else %>
    <%= render 'layouts/dash_header' %>
  <% end %>

		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
	<div class="container">
	  <div class="text-center">
	  	<div class="pad40"></div>
	    <h1>Public Service Loan Forgiveness</h1>
	    <div class="row">
	      <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
	        <h2 class="landing-subheader pad10">Government, 501(c)(3) non-profit, and public service workers, determine your eligibility for Public Service Loan Forgiveness (PSLF), then track and submit all in one place.</h2>
	      </div>
	    </div>
	  </div>
	  <div class="pad40"></div>
	  <div class="landing-btn-pad text-center">
	    <% if user_signed_in? %>
	    	<% if current_user.profile == nil %>
          <%= link_to "Let's Get Started!", new_profile_path, class: "btn btn-primary btn-lg" %>
        <% else %>
        	<%= link_to "My Dashboard", profiles_path, class: "btn btn-primary btn-lg" %>
        <% end %>
	    <% else %>
	      <%= link_to "LOG IN", new_user_session_path, class: "btn btn-default btn-lg" %>
			  <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	    <% end %>
	  </div>
	  <div class="pad40"></div>
	</div>
</div>
<div class="container">
  <div class="row">
    <div class="pad40"></div>
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 text-center">
	  	<div class="pad20"></div>
	  	<div class="landing-jumbo-text">
				<strong>PSLF, Streamlined.</strong>
	  	</div>
	  	<div class="col-lg-offset-1 col-lg-10 col-md-offset-1 col-md-10 col-sm-12 col-xs-12 text-center">
	    	<h4>We can’t wait to help you qualify, track, and receive your Public Service Loan Forgiveness (PSLF) benefit.</h4>
	    	<div class="pad20"></div>
	  	</div>
	  	<div class="col-lg-offset-1 col-md-offset-1"></div>
	    	<%= image_tag('mobileimg.png') %>
	  </div>
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
		  <div class="row">
		    <div class="pad80"></div>
			  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
			    <span class="glyphicon glyphicon-ok pull-right" aria-hidden="true"></span>
			  </div>
			  <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
			    <div class="landing-jumbo-text2 pad5">
			      <strong>Eligibility</strong></h1>
			    </div>
			    <p>Quickly determine if you’re loans, employment, and payments make you eligible for PSLF.</p>
			  </div>
		  </div>
		  <div class="pad40"></div>
		  <div class="row">
		    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
			    <span class="glyphicon glyphicon-list-alt pull-right" aria-hidden="true"></span>
			  </div>
			  <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
			    <div class="landing-jumbo-text2">
			      <strong>Forms</strong></h1>
			    </div>
			    <p>Access and store the necessary PSLF paperwork all in one convenient location.</p>
			  </div>
		  </div>
		  <div class="pad40"></div>
		  <div class="row">
			  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
			    <span class="glyphicon glyphicon-share pull-right" aria-hidden="true"></span>
			  </div>
			  <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
			    <div class="landing-jumbo-text2 pad5">
			      <strong>Track and Submit</strong></h1>
			    </div>
			    <p>Review, track, and ultimately submit for Public Service Loan Forgiveness.</p>
			  </div>
		  </div>
		</div>
	</div>
  <div class="pad80"></div>
  <div class="text-center">
    <% if user_signed_in? %>
	    	<% if current_user.profile == nil %>
          <%= link_to "Let's Get Started!", new_profile_path, class: "btn btn-primary btn-lg" %>
        <% else %>
        	<%= link_to "My Dashboard", profiles_path, class: "btn btn-primary btn-lg" %>
        <% end %>
	    <% else %>
	      <%= link_to "LOG IN", new_user_session_path, class: "btn btn-default btn-lg" %>
			  <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	    <% end %>
  </div>
  <div class="pad60"></div>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <div class="jumbotron app center">
    <h4>Progress</h4>
    <div class="row bs-wizard" style="border-bottom:0;">
      <div class="col-xs-2 col-xs-offset-3 bs-wizard-step complete">
        <div class="progress"><div class="progress-bar"></div></div>
          <div class="bs-wizard-dot">
            <span class="bs-wizard-step-num">1</span>
            <span class="glyphicon glyphicon-ok progress" aria-hidden="true"></span>
            <div class="bs-wizard-info pull-left">Eligibility</div>
          </div>
        </div>
        <div class="col-xs-2 bs-wizard-step complete"><!-- complete --> 
          <div class="progress"><div class="progress-bar"></div></div>
          <div class="bs-wizard-dot">
            <span class="bs-wizard-step-num">2</span>
            <span class="glyphicon glyphicon-ok progress" aria-hidden="true"></span>
            <div class="bs-wizard-info text-center">Forms</div>
          </div>
        </div>
        <div class="col-xs-2 bs-wizard-step active"><!-- complete --> 
          <div class="progress"><div class="progress-bar"></div></div>
          <div class="bs-wizard-dot">
            <span class="bs-wizard-step-num">3</span>
            <div class="bs-wizard-info pull-right">Tracking</div>
          </div>
        </div>
      </div> 
      <div class="pad50"></div>
      <div class="text-center">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
              <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                <h4><strong> 1. Eligibility Inputs<span class="caret"></span></strong></h4>
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
              <div class="panel-body">
                <h4><strong><u>Employment</u></strong></h4>
                <% @profiles.each do |profile| %>
                  <% if profile.user == current_user %>
                    <%= profile.employment %>
                  <% end %>
                <% end %>
                <div class="pad10"></div>
                <h4><strong><u>Loans</u></strong></h4>
                <% @profiles.each do |profile| %>
                  <% if profile.user == current_user %>
                    <%= profile.loans %>
                  <% end %>
                <% end %>
                <div class="pad10"></div>
                <h4><strong><u>Amount</u></strong></h4>
                <% @profiles.each do |profile| %>
                  <% if profile.user == current_user %>
                    <%= profile.amount %>
                  <% end %> 
                <% end %>
                <div class="pad10"></div>
                <% @profiles.each do |profile| %>
                  <% if profile.user == current_user %>
                    <%= link_to 'Edit Inputs', edit_profile_path(profile), class: "btn btn-primary btn-lg" %>
                  <% end %>
                  <% if current_user.profile == nil %>
                    <%= link_to "Add Eligibility Inputs", new_profile_path, class: "btn btn-primary btn-lg" %>
                  <% end %>
                      </tr>
                <% end %>
              </div>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingTwo">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <h4><strong>2. Employment Form<span class="caret"></span></strong></h4>
                </a>
              </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
              <div class="panel-body">
                <% if current_user.profile == nil %>
                  <%= link_to "Add Eligibility Inputs", new_profile_path, class: "btn btn-primary btn-lg" %>
                <% else %>
                  <% if (current_user.profile.employment == 'Government (fed, state, or local)' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'Government (fed, state, or local)' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'Government (fed, state, or local)' && current_user.profile.loans == "I don't know") || (current_user.profile.employment == 'Not-for-profit (Section 501(c)(3))' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'Not-for-profit (Section 501(c)(3))' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'Not-for-profit (Section 501(c)(3))' && current_user.profile.loans == "I don't know") || (current_user.profile.employment == 'AmeriCorps or Peace Corps' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'AmeriCorps or Peace Corps' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'AmeriCorps or Peace Corps' && current_user.profile.loans == "I don't know") || (current_user.profile.employment == 'Other qualifying public services' && current_user.profile.loans == 'Federal student loans') || (current_user.profile.employment == 'Other qualifying public services' && current_user.profile.loans == 'Both') || (current_user.profile.employment == 'Other qualifying public services' && current_user.profile.loans == "I don't know") %>
                    <h2>Based on your inputs, it looks like you probably qualify for Public Service Loan Forgiveness.</h2>
                    <div class="pad20"></div> 
                    <div class="media">
                      <div class="media-center">
                        <a href="https://studentaid.ed.gov/sa/sites/default/files/public-service-employment-certification-form.pdf", target= "_blank">
                          <span class="glyphicon glyphicon-download-alt" alt="PSLF Employment Verification Form">
                        </a>
                      </div>
                      <div class="pad10"></div>
                      <div class="media-body">
                        <div class="text-explanation-cert"> Click the icon above (opens new tab) for access to another employment verification form. </div>
                      </div>
                    </div>
                    <div class="pad30"></div>
                    <%= link_to 'See All My Forms', certs_path %>
                    <div class="pad10"></div>
                    <%= link_to 'Upload New Employment Verification Form', new_cert_path %>
                  <% else %>
                    <h4>Unfortunately, based on your Eligibility Inputs it seems like you may not be eligible for Public Service Loan Forgiveness at this time. You can review the requirements here.</h4>
                    <%= link_to 'Edit Eligibility Inputs', edit_profile_path(current_user.profile), class: "btn btn-primary btn-lg" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingThree">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                <h4><strong>3. Tracking Payments<span class="caret"></span></strong></h4>
                </a>
              </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingThree">
              <div class="panel-body">
                <h4>Once you get email confirmation from FedLoan (PHEAA) that your employment verification form was accepted, enter the number of verified payments you've already made and we'll help you track your payments moving forward.</h4>
                <%= render 'tracker' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="jumbotron app center">
		<p id="notice"><%= notice %></p>

		<p>
		  <strong>Employment:</strong>
		  <%= @profile.employment %>
		</p>

		<p>
		  <strong>Loans:</strong>
		  <%= @profile.loans %>
		</p>

		<p>
		  <strong>Amount:</strong>
		  <%= @profile.amount %>
		</p>

		<%= link_to 'Edit', edit_profile_path(@profile) %> |
		<%= link_to 'Back', profiles_path %>
	</div>
</div>